### ISSUE TITLE
Check all new maps for broken/bad spawn points

### ISSUE THREAD

**Issue by Badulundabad** [TheOldRealms/TOW_Core#100]
![broken_spawn](https://user-images.githubusercontent.com/62873054/133325761-1cf35f87-f0fb-4404-b8b2-64d5b3f902fd.PNG)

https://user-images.githubusercontent.com/62873054/133327630-f20c7f0f-5640-451c-a0ed-9f32ef56fb75.mp4

**Comment by Z3rca** [comment]
that is not well formulated. we need more detailed issues
