### ISSUE TITLE
Need to disable dropping/trading skeleton "armors"

### ISSUE THREAD

**Issue by Badulundabad** [TheOldRealms/TOW_Core#105]
![empty_legs](https://user-images.githubusercontent.com/62873054/133329573-46b0af9d-c535-4968-8217-6dfc07d988f1.png)
![broken_legs](https://user-images.githubusercontent.com/62873054/133329581-3ee5c95e-dfe2-4a77-a06f-9e008db6dc57.png)

**Comment by Z3rca** [comment]
this was theo old armory module, not relevant anymore
