### ISSUE TITLE
Summoned skeletons not counted towards mission victory

### ISSUE THREAD

**Issue by Badulundabad** [TheOldRealms/TOW_Core#112]
Words of some fan - "my necromancer went down, I lost the fight, but my summoned undead defeated the enemy though I still  "lost", was that intended?"

Also i saw that - Necromancer is against you. He summons skeletons. You kill him and win the battle, but skeletons are still alive and trying to kill you and your troops.

**Comment by martkartasev** [comment]
https://github.com/WarhammerTheOldWorld/TOW_Core/issues/118

**Comment by Badulundabad** [comment]
Fixed #150
