### ISSUE TITLE
Potential AI Bug when ordering wizard?

### ISSUE THREAD

**Issue by martkartasev** [TheOldRealms/TOW_Core#121]
Here's a freeze that happened during combat: I ordered formation 5 (a bright wizard) to a new position and the battle froze, but the music continued and it didn't generate an exception window. I don't know what the wizard was doing, he could have been casting/dismounted/knocked out just as I gave the order

https://cdn.discordapp.com/attachments/886588234820374539/888200401764110336/BattleOrdersFreeze.mp4

**Comment by fogbug** [comment]
A followup to this: I had a freeze happen in similar circumstances but I was not giving any orders at the moment of the freeze

https://cdn.discordapp.com/attachments/886588234820374539/888631343418859590/BattleFreeze2Lo.mp4

After the freeze you can hear the repeated sound fx of a light wizard's spell
