### ISSUE TITLE
Crash on World Map Zoom Change

### ISSUE THREAD

**Issue by debarr1** [TheOldRealms/TOW_Core#125]
This [video](https://streamable.com/h07c6r) shows such a crash, and the files for the crash are [here](https://discord.com/channels/702088927380635678/886588234820374539/888146316553777157). 

For me scrolling out on the world map often results in a crash, hence the 'gut' feeling to save seconds before.

In case hardware is an issue, my DxDiag is [here](https://pastebin.com/2035vtfD).  I know some have considered some problems could be nVidia specific.

Although this is common (~5-10% of the time), I cannot reliably reproduce this effect upon loading the save.

**Comment by debarr1** [comment]
This was reported on Discord by me on 2021-09-16 however I was not the first.  The following were reported on Discord;

The user [Firebringer4](https://discord.com/channels/702088927380635678/886588234820374539/888886694953242685) on 2021-09-18 says similar (has full crash dump).

The user [Sasch](https://discord.com/channels/702088927380635678/886588234820374539/888136463324155995) on 2021-09-16 also reported the similar issue (has full crash dump).

The user [Cadmium](https://discord.com/channels/702088927380635678/739460631224123443/887792183128776725) on 2021-09-15 says similar.

The user [Angus-Mac](https://discord.com/channels/702088927380635678/886588234820374539/886676346225434635) on 2021-09-15 says similar (has stack.txt).

The user [TheViking](https://discord.com/channels/702088927380635678/885929200165457970/886300040140836924) on 2021-09-11 says similar.

**Comment by debarr1** [comment]
A similar issue can be seen [here](https://streamable.com/k7v7tt) and the saves and logs are [here](https://drive.google.com/file/d/1-_ET3zTu9sLn6XziS4qPOF0C7dDGHPwn/view?usp=sharing).

**Comment by debarr1** [comment]
A similar issue can be seen [here](https://streamable.com/logmco) and the saves and logs are [here](https://drive.google.com/file/d/1-7hAS2cNMKbT5mlNzzRZSsPxVEL0kpsP/view?usp=sharing).

**Comment by debarr1** [comment]
Firebringer4, Sasch, Cadmium, Angus-Mac, and TheViking contacted to see if they would be willing to provide more information about their systems some kindly responded.
Cadmium has since wiped his computer, but says he uses an Nvidia card (GTX 1070).
[DxDiag_of_viking.txt](https://github.com/WarhammerTheOldWorld/TOW_Core/files/7188868/DxDiag_of_viking.txt) (GTX 1070)
[DxDiag_of_Sasch.txt](https://github.com/WarhammerTheOldWorld/TOW_Core/files/7189855/DxDiag_of_Sasch.txt) (GTX 1070)
[DxDiag_of_Firebringer4.txt](https://github.com/WarhammerTheOldWorld/TOW_Core/files/7190664/DxDiag_of_Firebringer4.txt) (GTX 2080 ti)
[DxDiag_of_Angus-Mac.log](https://github.com/WarhammerTheOldWorld/TOW_Core/files/7190822/DxDiag_of_Angus-Mac.log) (GTX 970)

**Comment by debarr1** [comment]
The user [Emperor Karl Franz ](https://discord.com/channels/702088927380635678/886588234820374539/888904692170629130) on Discord reported a crash not related to zooming in or out but just moving on the world map (full crash dump available at that link).
EDIT: He says that he uses 2 other mods, "RTS Camera" and "Realistic Battle AI", has been advised against.
EDIT: Dump since deleted.

**Comment by martkartasev** [comment]
https://github.com/TheOldRealms/TOW_CoreAssets/commit/915793761c8cf083900475baaddd3475ec5107c4
https://github.com/TheOldRealms/TOW_CoreAssets/commit/b61d1dc45f7959ded4239d3a844ca5cde0ea09e4
