### ISSUE TITLE
Crashes on Entering Town / Village

### ISSUE THREAD

**Issue by debarr1** [TheOldRealms/TOW_Core#127]
Crash as seen [here](https://streamable.com/jps6zi) entering the Town Waldenhof.  Save file (just seconds before crash) and logs located [here](https://drive.google.com/file/d/1-lyKThwb7EviC3bdBi5OY11PBwQVgxve/view?usp=sharing).

DxDiag for the crashing system is [here](https://pastebin.com/2035vtfD).

Many users have reported crashes on entering towns.

**Comment by debarr1** [comment]
A similar crash as seen [here](https://streamable.com/6vffua) entering Castle Drakenhof with logs and save files [here](https://drive.google.com/file/d/1-dYtnDnHhybSCUc8WoiaJARm1DyXZPi2/view?usp=sharing).

**Comment by debarr1** [comment]
A similar crash as seen [here](https://streamable.com/xiqim9) entering Castle Drakenhof with logs and save files [here](https://drive.google.com/file/d/1-bxeW5cSw7Qx5DJAhT_Gd4hIhJQ3AyTf/view?usp=sharing).

**Comment by debarr1** [comment]
Common comments from other users regarding crashing upon entering towns, such as those by [MEEDix66](https://discord.com/channels/702088927380635678/702151925147107389/888189242910597172)

**Comment by debarr1** [comment]
The Discord user [Emperor Karl Franz](https://discord.com/channels/702088927380635678/886588234820374539/888913914308460624) had a crash when entering Agheiten village (full crash dump).
EDIT: He says that he uses 2 other mods, "RTS Camera" and "Realistic Battle AI", has been advised against.
EDIT: Dump since deleted.

**Comment by debarr1** [comment]
The Discord user [Lef](https://discord.com/channels/702088927380635678/886588234820374539/888915056740433960) crashed entering a village (full crash dump).

**Comment by martkartasev** [comment]
WarhammerTheOldWorld/TOW_CoreAssets@9157937
WarhammerTheOldWorld/TOW_CoreAssets@b61d1dc

Most likely caused by the same problem as.
