### ISSUE TITLE
Crash on Raising Dead at Castle Drakenhof Graveyard

### ISSUE THREAD

**Issue by debarr1** [TheOldRealms/TOW_Core#130]
Development Branch
Crash whilst Raising Dead in the Graveyard at Castle Drakenhof as seen [here](https://streamable.com/rsdcn0) crash report files [here](https://drive.google.com/file/d/10E4S8YPyinAgJu_MCZHN3WovsettjTo1/view?usp=sharing).

When the save was loaded and this was repeated exactly, there was no crash.

The crash may not be anything to do with the function of Raising Dead in the Graveyard, and waiting may simply have the same effect, but neither produced a crash when repeated.

**Comment by martkartasev** [comment]
Most likely caused by the same things as

WarhammerTheOldWorld/TOW_CoreAssets@9157937
WarhammerTheOldWorld/TOW_CoreAssets@b61d1dc
