### ISSUE TITLE
Crash on Close Party / Troop Screen

### ISSUE THREAD

**Issue by debarr1** [TheOldRealms/TOW_Core#132]
Development Branch
Repeatable bug whereby, when sat stationary outside Castle Drakenhof, zoom out a little, and open party / troop screen, clicking Done then causes a crash before the world map is re-loaded / displayed.

1. [video](https://streamable.com/o1eamm) - [files](https://drive.google.com/file/d/1FR9YwxttRBuOYLbwYDDcp3M0mVE8IdYt/view?usp=sharing)
2. [video](https://streamable.com/7xng2r) - [files](https://drive.google.com/file/d/1zl-w02yaNFL-6isuJMwaAPjdYBOaa3Zn/view?usp=sharing)
3. [video](https://streamable.com/37sr78) - [files](https://drive.google.com/file/d/1dg3QQOlk0j85ofL4llUrRysGvnLLsV3V/view?usp=sharing)

**Comment by martkartasev** [comment]
WarhammerTheOldWorld/TOW_CoreAssets@9157937
WarhammerTheOldWorld/TOW_CoreAssets@b61d1dc
