### ISSUE TITLE
Crash when Rapidly Opening and Closing the Journal ("Journal Key Spam")

### ISSUE THREAD

**Issue by debarr1** [TheOldRealms/TOW_Core#133]
Development Branch.
No videos available of this.

New game created, and after moving on the world map slightly, the J key was pressed repeatedly (2-4 times a second) having the effect of opening and closing the Journal menu (about every other second).  With JetBrains dotMemory attached to the process, memory fluctuations could be seen with a slight trend increasing each time.  This was observed during screen share with Xenigma.
[1st](https://drive.google.com/file/d/15WQKD6ZzX0Uq1JTemv5xBNyJk0eNTdK1/view?usp=sharing) and [2nd](https://drive.google.com/file/d/18IHNxO3kxPvuzHmDyQ-lJlv8YvgkSe1H/view?usp=sharing) instances both have associated crash reports.

**Comment by martkartasev** [comment]
WarhammerTheOldWorld/TOW_CoreAssets@9157937
WarhammerTheOldWorld/TOW_CoreAssets@b61d1dc
