### ISSUE TITLE
Crash due to spawn path naming mismatch

### ISSUE THREAD

**Issue by debarr1** [TheOldRealms/TOW_Core#144]
Crash as seen [here](https://streamable.com/wsryyh) when attempting to join a battle defending "Villagers of Gerhof" in a villiage fight (Gerhof) against bandits.

[First](https://drive.google.com/file/d/10DOrABlqfAahlhBRCOJortHerL3aXJRB/view?usp=sharing) better exception and try to [continue](https://drive.google.com/file/d/19lGqD36urQD-eiE4wI6VpOTKR1xsQ215/view?usp=sharing).

Did not generate the usual TW crash dump, so save file is [here]( https://drive.google.com/file/d/10ezC-m6iay5lSfbXRmb8Ug2aMiTU0ECM/view?usp=sharing).

Upon loading save, always crashes when identical actions repeated.

1.6.2 - development branch.

**Comment by martkartasev** [comment]
![image](https://user-images.githubusercontent.com/30657311/134767044-0e6f2280-624a-4fe8-92e6-b4d2d33644a1.png)

**Comment by martkartasev** [comment]
Path spawnPath, comes from the variable

Mission._usedSpawnPath

Which is initially computed in 

Mission.FindSpawnPath() #Line 5229

**Comment by martkartasev** [comment]
![image](https://user-images.githubusercontent.com/30657311/134767158-d3d77d29-6eab-44a6-8fe5-b2c908357a83.png)
When debugging this, it fails to produce an input path. But the calls to

 this.Scene.GetPathWithName("spawn_path_0" + (object) num2); 
 etc
 
 Are engine level. So  I suspect we are missing something from our scene file.

**Comment by martkartasev** [comment]
![image](https://user-images.githubusercontent.com/30657311/134767300-f4bd7c09-c5df-4044-9f72-04aa437592e7.png)

**Comment by martkartasev** [comment]
The scene itself is missing certain spawn values most likely

**Comment by martkartasev** [comment]
https://github.com/TheOldRealms/TOW_EnvironmentAssets/commit/81d1f01451f4d0f40fab2b59a5a32065cb1e1ac1
