### ISSUE TITLE
Crash During Battle

### ISSUE THREAD

**Issue by debarr1** [TheOldRealms/TOW_Core#145]
1.6.2 development branch.
A crash as seen [here](https://streamable.com/wnteqd), when in a battle.  Whilst AI is fighting in distance, player hero and player troops are just moving.

TW crash report files including save [here](https://drive.google.com/file/d/10kyRP2_jQpTEk4mqcao3eEM9WkTtjrmZ/view?usp=sharing).  It did not generate a better exception report.

Reloading it I could not reproduce.

**Comment by martkartasev** [comment]
https://cdn.discordapp.com/attachments/886588234820374539/891243200885432330/2021-09-25_04.39.21.zip

Crashes similarly. On load though, no error. FIghts against chaos.

The reporter says he crashes every time. Possible problem with assets in his party?

**Comment by debarr1** [comment]
1.6.2 development branch.
Crash during another battle, a village scene as seen [here](https://streamable.com/koxwrm).

TW crash report files including save just before are [here](https://drive.google.com/file/d/10pwHoLsazcntX1zcNO2DHQQUQ3ep2FVq/view?usp=sharing).  It did not generate a "Better Exception" report.

Reloading it I could not reproduce.

**Comment by martkartasev** [comment]
https://discord.com/channels/702088927380635678/886588234820374539/891366315120549938

Another crash. Ended up being unrelated to spells.
Battle did contain chaos characters and archaon.

This has been reported earlier as well. Multiple crashes in the chaos portal fight.
My earlier comment also has the player fighting chaos raiders. (That one crashes ON LOAD though)
 Potential problem with some chaos assets?

**Comment by debarr1** [comment]
The discord user [RecklessCustard](https://discord.com/channels/702088927380635678/886588234820374539/891633361456623626) reported a crash in a battle (835 Empire vs 770 Vampire) outside Castle Drakenhof, his crash files including save are [here](https://drive.google.com/file/d/1p3gZQcZa18oqZRCO9l90Ju81OT2N4QSl/view?usp=sharing).

I reporduced this as seen [here](https://streamable.com/3lcv3w) by loading their save and my crash files (new save slightly closer to the fight) can be seen [here](https://drive.google.com/file/d/11BxKoldH3hlOyusLnkcos90Ca_o5ZFTu/view?usp=sharing).

Note that my video has an inspection of the roster.  No chaos present.

**Comment by debarr1** [comment]
The discord user [Vultz](https://discord.com/channels/702088927380635678/886588234820374539/891680163790749709) has reported a crash in a battle, despite them not being an active participant.

Chaos forces are present, and it is a large battle (1388 vampire vs 784 empire).

I have reloaded their save and reproduced a crash as seen [here](https://streamable.com/qb2amx) (roster visible at about 02:45) and the crash files are [here](https://drive.google.com/file/d/11NWofEKkBrJH1C8fu3t7xid-_SV0e0da/view?usp=sharing).

**Comment by debarr1** [comment]
The Discord user [Beany](https://discord.com/channels/702088927380635678/886588234820374539/891790261036929115) reported a crash between his party and 10 + 10 outlaws.  His crash file is [here](https://drive.google.com/file/d/1oIfkoPXNd4lj14a_bkJH7tXC_2CNf8c2/view?usp=sharing).

It had other mods present however, namely UIExtenderEx and ButterLib.  Advised against this for troubleshooting purposes.  As such I did not attempt to reproduce.

**Comment by debarr1** [comment]
The Discord user [Nelynonwé of Tir ná Lia](https://discord.com/channels/702088927380635678/886588234820374539/892041255645765632) reported a crash with files [here](https://drive.google.com/file/d/11bVX3vZtoobB_s1I29NzUSM7YDd0efQg/view?usp=sharing).

Banner Color Persistence / BannerPaste  mods active, advised against.

Reports frequent crashes in battles, notes position and troop type may be factors and notes visual glitches in his last crash.

He notes heavy use of cavalry, like some users in issue #149.

**Comment by debarr1** [comment]
The Discord user [R4MPZY](https://discord.com/channels/702088927380635678/886588234820374539/892156545406738452) has provided crash files [here](https://drive.google.com/file/d/1bZGrY411YbqOPLpFLvglxypjWz94Fkhe/view?usp=sharing).

He states that he recieved this crash as a soft crash after a large seige battle.  The full post is linked above.

**Comment by debarr1** [comment]
The Discord user [aWeisGuy](https://discord.com/channels/702088927380635678/886588234820374539/894414788799660052) reports crashes during battle, at point of hit with Grave Guard great sword.  TW crash report [here](https://drive.google.com/file/d/1S6vPIMLF0vDWbDvL6VW_7OIyepMsLByN/view?usp=sharing).

**Comment by debarr1** [comment]
The Discord user [DeltaScorch](https://discord.com/channels/702088927380635678/886588234820374539/894439588444139561) reports crashes during battle, at during troops routing / battle end. TW crash report [here](https://drive.google.com/file/d/1dsAN5NoexyAxssYLu7jdpvYO_voP7Krp/view?usp=sharing).

**Comment by debarr1** [comment]
The Discord user [TrebleMuffin](https://discord.com/channels/702088927380635678/886588234820374539/894486742260928523) reports crashes during a larger battle (~200 units), at during troops routing / battle end. Submits multiple TW crash reports;
- [1](https://drive.google.com/file/d/1fekT54Oji3ucRs0TxrjxZuDYUCkYKpC-/view?usp=sharing)
- [2](https://drive.google.com/file/d/1fZyp7uFf0mK9SYohGxBmYPD9-deqzFD1/view?usp=sharing)
- [3](https://drive.google.com/file/d/1tF64WTnXhFkBp0rPkhi1RIHMsHQIKaMq/view?usp=sharing)
- [4](https://drive.google.com/file/d/1kR6cheMl10tWrOjVLIQMr0lD7lWAo6l2/view?usp=sharing)

TrebleMuffin describes another crash report [here](https://drive.google.com/file/d/1uZyPM-mrgAM0n_5XAvsKYVatVc7WhsaT/view?usp=sharing), for the same battle, where he describes a "crash type 2" / soft crash (error message but game still plays in background).  Happened around time when some enemy troops started fleeing before and of the battle.

**Comment by debarr1** [comment]
Discord user [greasyfatpenguin](https://discord.com/channels/702088927380635678/886588234820374539/895027813432819763) reports a crash "_Siege on Fort Bracher. Shooting crossbow next to fort walls_" and supplies file [here](https://drive.google.com/file/d/134jlBGitvQNfpQLdaq2on4sJZRYEMyYq/view?usp=sharing).

On playing slightly further and making a new save point just before the battle, I died, and watched the battle progress until a crash, TW files here.  No Better Exception window was generated and unfortunately I was not recording at the [time](https://drive.google.com/file/d/133tfKWAm9EzNWx4P0iEnEJqRWEbRNikb/view?usp=sharing).

**Comment by debarr1** [comment]
This is an update of this issue as part of an update on current major issues as requested by Xenigma.

This update refers to;
TOR_Armory (development)
TOW_Core (1.6.4)
All other modules on development.
All above pulled up to 1210 hours (UTC +0) 2021-10-10

It is likely that some of these crashes relate to #149.  Some others may not.  As noted in issue #149, when issue #162 is resolved, testing of any issue here would become much more efficient.  It is difficult to identify a single issue in these however.

As such I recommend that this issue stay open for a short period of testing before being closed if nothing further / useful can be collected for the current release.
