### ISSUE TITLE
Crash on Bandit Hideout with Necromancer Present

### ISSUE THREAD

**Issue by debarr1** [TheOldRealms/TOW_Core#154]
As reported by discord user R4MPZY on 1.6.2 by discord PM and they supplied their save file [here](https://drive.google.com/file/d/11zQGdQUj_2fnpwa8mo4om_SZPBmx42bX/view?usp=sharing).

The bug as reported is a crash upon reaching the boss fight in a hideout if a necromancer is in the party and summon skeletons is used by the player.

I have reproduced it in 1.6.2-development.  The video can be seen [here](https://streamable.com/i76qw6) - note that no crash files were generated just the Better Exception report [here](https://drive.google.com/file/d/13W86TWOg99jsH554LAeZiqnK5Us7kzcs/view?usp=sharing).

This was repeated again as seen [here](https://streamable.com/bvptb6), Better Exception [here](https://drive.google.com/file/d/128ABmtDoe-SUtnF-KkW3kA2xs6jJ7e1q/view?usp=sharing), however no skeletons were raised.

This was repeated again as seen [here](https://streamable.com/vo5e3t), however no Necromancer was present as well as no raising.  **It did not crash**.  Save file post hideout was made [here](https://drive.google.com/file/d/12FPKHbX1Q1BLlpvadxOwldocG_6MmePb/view?usp=sharing).

This was repeated again but with a number of reductions (no party other than necro, no equipment other than sword and shield) and necromancer only, no raising again, as seen [here](https://streamable.com/7hch4j).  The save file in this reduced state is [here](https://drive.google.com/file/d/12fykOZ4iGx7zP0cbKPJBu7QNv7zQY6Zd/view?usp=sharing).  It actually started the boss cut scene this time and showed a second of it before crash, as well as the Better Exception window.  Seconds after the recording ends a TW crash report windows appeared, and in my excitement in seeing a crash report window, I clicked yes before saving the Better Exception which closed the game including the Better Exception window but I did see the first line included the same "Source: System.Core" and "Sequence contains no elements" under the Reasons heading before I reaslised what I had done and it disapeared.  Crash report files can be seen [here](https://drive.google.com/file/d/12SJ8PgL6zwdMFQKxrjv0hbqohZ0TpDgv/view?usp=sharing).

How can the necromancer presence affect hideout boss spawn / cut scene?

**Comment by Badulundabad** [comment]
fixed 5f0c0478fb586979f0d9e5814397beb87966601d
