### ISSUE TITLE
Not All Necromancers Summon Skeletons in Battle

### ISSUE THREAD

**Issue by debarr1** [TheOldRealms/TOW_Core#155]
Reported by Discord user [Qzeto](https://discord.com/channels/702088927380635678/886588444862734366/893257588098093126) which includes his own video, he has 3 necromancers in party, but only 2 summon.

Save file [here](https://drive.google.com/file/d/12gCNkd2eT5FwNAdNZgIkRuN31OmDhNH1/view?usp=sharing).

To speed up testing I created a smaller army (kicked all but necromancers, removed items etc) to hunt bandits.  Small save [here](https://drive.google.com/file/d/12it0AfnyNwUhQ05VIYxZZU94xhfwj7cm/view?usp=sharing).

The party now consists of;
1. Elger
2. Rudusch
3. Dominicus
...who are (3 necromancers).

Entering a battle always (same battle fought 4 times) results in Dominicus not casting, as his colleagues start raising skeletons as seen [here](https://streamable.com/2f37b3).

Kicking Elger or Rudusch does not cause Dominicus to start casting, as seen [here](https://streamable.com/nlec11).

Why is Dominicus work shy?  Expected that he would summon skeletons.

**Comment by debarr1** [comment]
Qzeto supplies a further video demonstrating similar issue with 4 necromancers (only first 2 recruited cast) [here](https://www.youtube.com/watch?v=CJUJ4vaREPU).

**Comment by debarr1** [comment]
Qzeto supplied a second save with 4 necromancers in - this is a continuation of the previous save.  I remove some extra characters (like the wight king) and save [here](https://drive.google.com/file/d/1yeDnPGuW1Imo4IGc_T7hG6ckiCshIltV/view?usp=sharing).  The same issue can be seen [here](https://streamable.com/fzs7fn) but now another necromancer is present Gotschalg.  The party is now;
1. Elger
2. Rudusch
3. Dominicus
4. Gotschlag

In addition to Dominicus, now Gotschlag does not cast.  It is as though only the first 2 necromancers to party will cast.

**Comment by martkartasev** [comment]
After investigating the code, it seems like the heroInfo from ExtendedInfoManager does not contain information about these characters and they are therefore not recognized as casters / ability users.

Any ideas @hunharibo ?

**Comment by Z3rca** [comment]
I believe this is fixed some time ago. Mayor overalls to the Spell caster AI
