### ISSUE TITLE
Crash After Battle When Returning to World Map

### ISSUE THREAD

**Issue by debarr1** [TheOldRealms/TOW_Core#159]
The Discord user [Punisher](https://discord.com/channels/702088927380635678/886588234820374539/894784865239728138) reported that their game crashed upon loading the village scene (Bernloch) for a villiage battle defence against chaos - their crash files are [here](https://drive.google.com/file/d/1_skgPdxNEzoii2SZVqj5ryX4Qw1K3xt4/view?usp=sharing).

I was unable to reproduce this, as the scene loaded fine.  In attempting to do so however I did get a crash upon returning to the world map after being defeated as seen [here](https://streamable.com/075vaw) - slight edit to skip through horse archery cheese.

My crash files did not generate but the Better Exception Window did and is [here](https://drive.google.com/file/d/1ozObF4t4XIH9sRDKdEfTf_SdLHmyVIOw/view?usp=sharing) and repeated [here](https://drive.google.com/file/d/1Gf5af1fxexbQHq2Zs33xaMLB0tZGkN1J/view?usp=sharing).

1.6.2-development

**Comment by debarr1** [comment]
As requested, if the above file is saved (seen [here](https://drive.google.com/file/d/12yJ1A1MvnjDSl4T4hbX0xETQEImYJPak/view?usp=sharing)) on my version it still crashes as seen [here](https://streamable.com/7in2vc) (or on Yandex [here](https://disk.yandex.com/i/xppnwl145hK7Fg)) with the better exception as seen [here](https://drive.google.com/file/d/1Xb5WwmgnYv3O5qBWylijGa_ArK9in7Qh/view?usp=sharing).

**Comment by Badulundabad** [comment]
fixed 67f966d07d64f2ed36606a526f27604ad5608975
