### ISSUE TITLE
Save Game Crashes on Load

### ISSUE THREAD

**Issue by debarr1** [TheOldRealms/TOW_Core#160]
The Discord user [RevMeta](https://discord.com/channels/702088927380635678/886588234820374539/895026124491489300) reports that one of his save games crashes on attempting to load, his provided files are [here](https://drive.google.com/file/d/1Jx8B2mEAJ7Ye3yh3q7Fnu243UKOE_yyh/view?usp=sharing).  Confirmed in 1.6.2-develop as seen [here](https://streamable.com/qwxcj6) with my TW crash report [here](https://drive.google.com/file/d/1Ym7NlUUkdZPl02nev_lPrrlz2da670tt/view?usp=sharing).

He did indicates that he was only using the required mods when he made the save.

**Comment by Badulundabad** [comment]
i think his save file is broken
