### ISSUE TITLE
Crash When Exit to Main Menu from "Build Shader Cache" Battle Scene

### ISSUE THREAD

**Issue by debarr1** [TheOldRealms/TOW_Core#166]
TOR_Armory (development)
TOW_Core (1.6.4)
All other modules on development.
All above pulled at 1840 hours (UTC +0) 2021-10-11

When exiting from the escape menu from the "Build Shader Cache" battle scene, there is a crash as shown [here](https://streamable.com/dh9loq).  Whilst no TW crash report file was generated, the Better Exception report is [here](https://drive.google.com/file/d/1gc_0XsQ8o74-fpU12lF7Hm3s-pr602MK/view?usp=sharing).  This is reproducible.

Retreating from the battle does not cause a crash.

**Comment by R4MPZY** [comment]
I tried to reproduce this and out of the 2 times i tried it, it crashed both times when trying to 'quit' the battle instead of retreating.

My BE report is [here](https://drive.google.com/file/d/1Rrs0ziYsoUX_vwWXaxvzB3u5zktWgV8X/view?usp=sharing)

**Comment by hunharibo** [comment]
this was fixed
