### ISSUE TITLE
Animated Skeletons from Post Battle Occasionally do not Stack with Animated Skeletons from Graveyards

### ISSUE THREAD

**Issue by debarr1** [TheOldRealms/TOW_Core#167]
TOR_Armory (development)
TOW_Core (1.6.4)
All other modules on development.
All above pulled at 1840 hours (UTC +0) 2021-10-11

Sometimes animated skeletons recieved post battle do not stack with those recieved from raising from graveyards as seen [here](https://streamable.com/s6zep1).  That video shows the main party of skeletons who were raised from Castle Drakenhof Graveyard fight a battle.  Afterwards 1 Animated Skeleton was recieved but would not stack in the party.

Battles after this would produce "post battle" Animated Skeletons that would stack with "graveyard" Animated Skeletons.

Another [video](https://streamable.com/68bv4y) of it happening again.

These troop stacks are different and have different troop trees as seen [here](https://streamable.com/8gi9x4).

**Comment by debarr1** [comment]
As above, but 24 Empire Outlaws attacked repeatedly (manual battle F1->F3) by reloading this save [here](https://drive.google.com/file/d/1XDzB1aP2EDDzsIFe3I9TaRRg84QkT_c1/view?usp=sharing) 12 times;
21x Empire Outlaw
3x Empire Outlaw Captain

Outcomes
**1x** Nothing raised
**1x** 1 Animated Skeleton with no progression troop tree.
**1x** 2 Animated Skeleton with no progression troop tree.
**2x** 2 Animated Skeleton with no progression troop tree and 2 Animated Skeletons with troop tree.
**1x** 3 Animated Skeleton with no progression troop tree and 2 Animated Skeletons with troop tree.
**2x** 1 Animated Skeleton with troop tree.
**3x** 2 Animated Skeletons with troop tree
**1x** 3 Animated Skeletons with troop tree.

**Comment by Badulundabad** [comment]
fixed a68bacb76aee0987e194b9c5bad2375069d5001d
