### ISSUE TITLE
Unable to vote for fiefs and kingdom policies ( get stuck in policy screen )

### ISSUE THREAD

**Issue by R4MPZY** [TheOldRealms/TOW_Core#173]
TOR_Armory (development)
TOW_Core (1.6.4)
All other modules on development.

All above pulled at 12:00 hours (UTC +2) 2021-10-13

I started a fresh VC campaign after gaining access to the experimental/1.6.4 branch, as soon as the VC AI conquered Leicheberg on their own ( i cannot help because its a custom scene ) i noticed this issue for the first time as seen as [here](https://streamable.com/gfx1ug) ( i do apologize for the stream sound in the background, its my first time doing this so rookie mistake ).

I didn't think much of it at first but after playing for a couple of hours it seemed odd that there was no decision for Leicheberg but i kept getting the popups but they disappear right after.

I wanted to test a bit more before posting so i decided to take over Fort Bracher with my own clan and now i get 2 popups that disappear right after so i made a compilation video of the most notable times it happened, and at the very end i was able to finally click on the popup before it vanishes, but i just get a notification that the vote is no longer relevant as seen [here](https://streamable.com/jp7b2r)

I will make a brand new Empire character and try to reproduce this again.

**Comment by R4MPZY** [comment]
TOR_Armory (development)
TOW_Core (1.6.4)
All other modules on development.

All above pulled at 14:43 hours (UTC +2) 2021-10-13

As stated above i made a brand new Empire Bright Wizard character, i only used 1 mod called CharacterTrainer to import enough clan renown so i can instantly join Stirland and some money to keep my troops, I joined them in taking Fort Bracher and the issue is reproduceable as seen [here](https://streamable.com/yzgm1i)

**Comment by debarr1** [comment]
The Discord user [Ryan Mitchell | Quiet Brook](https://discord.com/channels/702088927380635678/891631177352478731/900214353456939059) also reports;
"_I am in a kingdom decision and have selected what I want to vote for and how much influence i want to spend but the "done" button is still grayed out?_"

**Comment by R4MPZY** [comment]
The discord user [Warl0rd13](https://discord.com/channels/702088927380635678/886588234820374539/900886530262978572) has confirmed this bug aswell.

"_I have an odd bug in my vampire playthrough; when a settlement/castle is taken it is automatically given to Mannfred without a council being held. Now, while that might be in character for the guy I hold the suspicion of it being a bug because I get spammed with constant notifications of an election taking place to decide who owns it that then say it's declared no longer valid when I try to click it._"

**Comment by R4MPZY** [comment]
It would seem discord user [Joey Mangz](https://discord.com/channels/702088927380635678/739460631224123443/901049562607788032) is having these issues aswell, glad to know i'm not the only one :P 

"_I was just going to bring this up. The kingdom decision are being settled immediately. As soon as the alert pops up, it is resolved. If I click on it I get a message saying the decision is no longer relevant. i havent been able to take part in a single kingdom decision yet_"

**Comment by R4MPZY** [comment]
It would seem this issue isnt solely related to voting for fiefs, but the entire voting system as seen [here](https://streamable.com/fm9nwz) . So i'll change the title name and add these issues together for the time being.
