### ISSUE TITLE
Crash in Caravan Defence Battle

### ISSUE THREAD

**Issue by debarr1** [TheOldRealms/TOW_Core#181]
All modules on development branch pulled at 2350 hours (UTC +0) 2021-10-17.

When defending the caravan, the game will crash as seen [here](https://streamable.com/c320jg).  The battle is nearly all muskets (about 130 men) and some archers against 40 raider horsemen.  This generated the better exception report [here](https://drive.google.com/file/d/146bpaTC7x6W8ed5PlDZWwdHue4dMAwJO/view?usp=sharing).  The save game just before the crash is [here](https://drive.google.com/file/d/1y7_GAQPUWKwJAdJ3mX541lZCSlXbGsYd/view?usp=sharing).

This was repeated 4 times crashing each time.  The second time was recorded [here](https://streamable.com/kntteb) better exception [here](https://drive.google.com/file/d/1jaEOglFh3v-Q0T2Xv90qqabtr3ZN1Cul/view?usp=sharing), showing the troops present in the battle from the 'tab screen'.

YandexDisk links for the above are [here](https://disk.yandex.com/i/CbP7EMApugMFzA) for number 1, and [here](https://disk.yandex.com/d/W6v_6TwCdlLoCw) for number 2.

The third fight generated a TW Crash Report, [here](https://drive.google.com/file/d/14FDrQrAtMrJOSyQGY3YrjR6S3N5EFDAP/view?usp=sharing).

After this fight (skipping by autoresolve), the caravan was attacked again at the second destination, similar circumstances as seen [here](https://streamable.com/yis7sj), better exception [here](https://drive.google.com/file/d/1DyAEx0UD1mJl8E61CuigSfEN7I3TS6eg/view?usp=sharing).

**Comment by debarr1** [comment]
[Xenigma](https://discord.com/channels/702088927380635678/846055253581103115/899246585588887654) states this is cased by dismemberment (issue #149).

**Comment by martkartasev** [comment]
> [Xenigma](https://discord.com/channels/702088927380635678/846055253581103115/899246585588887654) states this is cased by dismemberment (issue #149).

The issue is about dismemberment but the root cause if different. The better exception window here indicates a potential null pointer problem.

**Comment by Badulundabad** [comment]
It seems like it's fixed by #197
