### ISSUE TITLE
Crash Relating to Bright Wizard Fireball

### ISSUE THREAD

**Issue by debarr1** [TheOldRealms/TOW_Core#190]
All modules on development branch pulled at 0700 hours (UTC +0) 2021-10-19.

The Discord user [some loser](https://discord.com/channels/702088927380635678/886588234820374539/899822420742004747) reports "_having a spell caster companion ( i found it w the brightwizard) that casts causes a crash_" but it is otherwise not described.

The Discord user [DrJoshPearson](https://discord.com/channels/702088927380635678/886588234820374539/899900081006841856) reports that "_...it is crashing when my Bright Wizard Companion starts to cast his fireball._" and submits a TW Crash dump.  I have reloaded their save from their [TW crash report](https://drive.google.com/file/d/1uCIF4HFfSp-Kp1aEjFVgxD2Ge2XfAEBB/view?usp=sharing), and removed all troops from his party (my save [here](https://drive.google.com/file/d/1kHYazgISlPeHSxxsM1odQbmhf-QRkhH4/view?usp=sharing)), and engaged a different enemy party.

Crash upon resolving of Bright Mages fireball upon enemy as seen [here](https://streamable.com/4r43zm) (YandexDisk [here](https://disk.yandex.com/d/4WghPXsjLWWVaQ)) which produced the three better exception reports [1](https://drive.google.com/file/d/1ArTIg0wYbv3wKzeTmRq1-Cj3y0Mzv3Hl/view?usp=sharing), [2](https://drive.google.com/file/d/1ERIUVVPpVd4_yGPKSya8OiUi466tr1Wn/view?usp=sharing), and [3](https://drive.google.com/file/d/1PYpzhmBvouvT1Rn1n7M0leySZvofs3b1/view?usp=sharing).

This was repeated against the same party 2 more times with the same result.

I am awaiting confirmation from some loser and DrJoshPearson that this is the same issue.

I have not performed any testing if the crash occurs on player casting of the same spell as the Discord user [Ainz Ooal Gown](https://discord.com/channels/702088927380635678/886588234820374539/899936993004359700) has reported "_Happens if it comes from the player too._"

**Comment by martkartasev** [comment]
https://github.com/TheOldRealms/TOW_Core/commit/7c87b44095e0d8769cee90eb301db86a3cdfc042

Submitted as a fix
