### ISSUE TITLE
Very small font size for winds of magic and creating custom weapons in smithy

### ISSUE THREAD

**Issue by R4MPZY** [TheOldRealms/TOW_Core#193]
The size of the text for winds of magic has been drastically reduced in size to the point its barely readable or visible as seen below.

I've added the visual tag as i think this is what it is ? Sorry if i'm wrong

![TORSmallFont](https://user-images.githubusercontent.com/63518948/137996058-8077b50a-0b73-4971-9149-175613562a19.jpg)
![TORSmallFont1](https://user-images.githubusercontent.com/63518948/137996062-62373637-8e96-4a9e-8c48-2f88455e58d0.jpg)

**Comment by hunharibo** [comment]
Fixed first part of this with: https://github.com/TheOldRealms/TOW_CoreAssets/commit/a8de992e6de08e958f19d8706872ef2bc8ac3515
