### ISSUE TITLE
Hideout battle issue when reaching leader part

### ISSUE THREAD

**Issue by R4MPZY** [TheOldRealms/TOW_Core#194]
All modules on development.

All above pulled at 14:15 hours (GMT +1) 2021-10-20

The user [Bill](https://discord.com/channels/702088927380635678/762735557549621278/900281258192543764) reported this issue in the questions channel and i was able to reproduce this every hideout battle so far, i made a small clip of 2 different battles to show the issue [here](https://streamable.com/uokcxs)

I show the units i take into battle and then cut towards the end, at the 00:23 mark you can see i get a "You have won the battle" popup when i defeated the last of the initial bandits ( before the leader spawns ) and when i press TAB ( which you normally do to end a battle you've won ) i immediately get the victory screen even though you see the leader spawn in the background.

Starting at the 00:43 mark you see me choosing my units for another hideout battle and skipping towards the end but this time i do not press tab and choose to fight them all, at which point you see all my soldiers i took into battle still celebrating because the game says we've already won, as the bandits are attacking.

**Comment by Badulundabad** [comment]
fixed #196
