### ISSUE TITLE
Empire clan(s) joining Vampire Counts

### ISSUE THREAD

**Issue by R4MPZY** [TheOldRealms/TOW_Core#195]
All modules on development.

All above pulled at 12:30 hours (GMT +1) 2021-10-21

Today i was just roaming around on my VC campaign when i suddenly saw the popup that Oststirlander joined the VC, when i finally came back to my senses after laughing a bit i made a screenshot and posted about it in  #testing-feedback to make sure its an issue, its a vanilla thing i know that can happen, but probably not a good thing in TOR haha.

I did notice on my second screenshot that Helman Ghorst and myself have 98 and 100 relations with Count Petr, maybe that somehow influences the decision? I'm only around a 100 days into this campaign, and my previous campaigns before i became a tester were around 300 days and never saw this before.

I added the label "bug" although i'm not entirely sure it is, since its a vanilla thing.
![TORtraitors](https://user-images.githubusercontent.com/63518948/138266142-2d081c62-11d0-48bb-813a-5384692c7f14.jpg)
.
![TORtraitors1](https://user-images.githubusercontent.com/63518948/138266152-5f13ba9d-b5e9-423e-9f11-7566715a4e5e.jpg)

**Comment by Z3rca** [comment]
it could be discussable if this should be actually a feature... by switching faction they automatically become a vampire.
