### ISSUE TITLE
Player clan AI party recruiting issue

### ISSUE THREAD

**Issue by R4MPZY** [TheOldRealms/TOW_Core#198]
TOR_Armory : Development branch
TOR_Environment : Development branch
TOW_Core : Development branch
TOW_CoreAssets : Development branch
TOW_Prenative : Development branch

All above pulled at 13:00 hours (GMT +1) 2021-10-22

So i recently started noticing my clan AI parties do not have any skeletons after a set period of time ( losing most of their troops in a battle etc ) since i usually gave them quite a few.

So in this [clip](https://streamable.com/ej7h6x) i made a companion a new party leader, without any troops and simply follow him around to see what he recruits, all i see are sylvanian recruits/peasants/archers/state troopers and at the very end empire troops, but not a single skeleton when visiting towns/villages or after battles, even though VC parties should have this feature ( maybe player clan is exempt somehow? )

**Comment by Badulundabad** [comment]
fixed 239c71a2789d3f152486f7de6dc84abf29fe7449
