### ISSUE TITLE
Magic spells against destructible object cause crash

### ISSUE THREAD

**Issue by Z3rca** [TheOldRealms/TOW_Core#210]
occured when hitting siege towers, rams or merlons of the wall.

**Comment by Jasonleh99** [comment]
I can't seem to reproduce this issue, do you know if this is still relevant?

Spells also don't seem to deal **any** damage to destructible objects, so that may be why this crash isn't occurring anymore.

**Comment by Z3rca** [comment]
I think this was fixed wioth 1.6.1
