### ISSUE TITLE
CTD when the army a player is part of finishes raiding

### ISSUE THREAD

**Issue by R4MPZY** [TheOldRealms/TOW_Core#213]
All modules on development.

All above pulled at 14:30 hours (GMT +1) 2021-12-08

Hey all, i've been getting several reports of issues related to village raiding when part of an army ( i asked them to try raiding on their own and that causes no issue ).

As soon as the army finishes raiding they CTD, i asked to share their saves and tried reproducing it but on my branch the AI lord simply stops the raiding and moves away even if the raid was nearly done ( someone saved it 2 seconds before they'd finish but he still leaves when i try it myself ).

They did provide a crashlog as shown [here](https://drive.google.com/file/d/1CvE9OS1FpHoIbXVt2SHYspUvZiC75Cr_/view?usp=sharing).

**Comment by R4MPZY** [comment]
I have made a new Bannerlord folder so i can freely play 1.6.4 ( current release for the masses ) and have my normal folder for 1.7.0 so i can still test without having to constantely switch, that said i have finally been able to reproduce this issue.

[Here](https://drive.google.com/file/d/1dbfHv6CuWjTT7_UHSvmE21eTLK9usckO/view?usp=sharing) is the rar file with the save and my own BEW crashlog

**Comment by Jasonleh99** [comment]
Issue seems to still be active, I'm sending out a fix.
