### ISSUE TITLE
Reproducible Crash: GetElementCopyAtIndex

### ISSUE THREAD

**Issue by Z3rca** [TheOldRealms/TOW_Core#245]
![grafik](https://user-images.githubusercontent.com/43908801/165852457-89d6503e-9fb4-42af-bbc6-710313967f31.png)

Reproduction: This seems nothing directed to the player party or any player interaction. Marius Leitdorf Party will elicit an IndexOutOfRange  Exception, by the time the player can travel from the current position to Grissenwald.  Will investigate this more if needed.

**Comment by hunharibo** [comment]
Could you detail the reproduction steps for this starting from a new game?

**Comment by Z3rca** [comment]
was solved here 

https://github.com/TheOldRealms/TOW_Core/blob/0fb4d4d5a06ba2e377fa30ad0ba0b279217a0efd/CSharpSourceCode/HarmonyPatches/CharacterObjectPatches.cs#L41
