### ISSUE TITLE
[BUG] Crash after leaving the vampire village on campaign map №2. 

### ISSUE THREAD

**Issue by AJIexander** [TheOldRealms/TOW_Core#252]
**Describe the bug**
I went to take a quest to "help with deserters" in a vampire village. After the download was completed, when leaving the village, a crash occurred on the map of the company.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
[rgl_log_errors_5032.txt](https://github.com/TheOldRealms/TOW_Core/files/8742085/rgl_log_errors_5032.txt)
[rgl_log_5032.txt](https://github.com/TheOldRealms/TOW_Core/files/8742086/rgl_log_5032.txt)

**Comment by Jasonleh99** [comment]
Same issue as https://github.com/TheOldRealms/TOW_Core/issues/251
