### ISSUE TITLE
[BUG] Crash after the end of the battle with the bandits (Outlaw Party) when loading the game on the campaign map.

### ISSUE THREAD

**Issue by AJIexander** [TheOldRealms/TOW_Core#253]
**Describe the bug**
Crash after the end of the battle with the bandits when loading the game on the campaign map.

**To Reproduce**
1. Get in the fight with the "Outlaw Party".
2. Win the battle.
3. The game crashes when loading onto the campaign map.

**Expected behavior**

**Screenshots**

**Additional context**
[rgl_log_errors_4016.txt](https://github.com/TheOldRealms/TOW_Core/files/8742073/rgl_log_errors_4016.txt)
[rgl_log_4016.txt](https://github.com/TheOldRealms/TOW_Core/files/8742074/rgl_log_4016.txt)

**Comment by Jasonleh99** [comment]
Not reproducible on our end, closing now

Reach out to us on discord and we can help you personally
