### ISSUE TITLE
[BUG] Crash after completed the dialogue to get the quest (Deliver the herd to Waldenhof)

### ISSUE THREAD

**Issue by AJIexander** [TheOldRealms/TOW_Core#256]
**Describe the bug**

**To Reproduce**
1. Went to the village Mikalsdorf
2. Clicked to "visit" NPC 
3. Completed the dialogue to get the quest (Deliver the herd to Waldenhof)
4. Pressed "Tab"
5. Crash

**Times Reproduced**
[times reproduced] / [number of attempts]

**Expected behavior**

**Screenshots**

**Additional context**
[rgl_log_6240.txt](https://github.com/TheOldRealms/TOW_Core/files/8747243/rgl_log_6240.txt)
[rgl_log_errors_6240.txt](https://github.com/TheOldRealms/TOW_Core/files/8747244/rgl_log_errors_6240.txt)

**Save**
[Vampire_I.zip](https://github.com/TheOldRealms/TOW_Core/files/8747255/Vampire_I.zip)

**Comment by Jasonleh99** [comment]
Not reproducible on our end, closing now

Reach out to us on discord and we can help you personally
