### ISSUE TITLE
[BUG]  Crash after completed the dialogue to get the quest (Messinghof Needs Tools)

### ISSUE THREAD

**Issue by AJIexander** [TheOldRealms/TOW_Core#257]
**Describe the bug**
 Crash after completed the dialogue to get the quest (Messinghof Needs Tools)

**To Reproduce**
1. Went to the village Messinghof
2. Clicked to "visit" NPC 
3. Completed the dialogue to get the quest (Messinghof Needs Tools)
4. Immediately after the dialogue, pressed "Tab"
5. Crash

**Times Reproduced**
The problem could not be reproduced.

**Expected behavior**

**Screenshots**

**Additional context**
[rgl_log_8692.txt](https://github.com/TheOldRealms/TOW_Core/files/8747273/rgl_log_8692.txt)
[rgl_log_errors_8692.txt](https://github.com/TheOldRealms/TOW_Core/files/8747274/rgl_log_errors_8692.txt)

**Save**
[Vampire_II.zip](https://github.com/TheOldRealms/TOW_Core/files/8747268/Vampire_II.zip)

**Comment by Jasonleh99** [comment]
Not reproducible on our end, closing now

Reach out to us on discord and we can help you personally
