### ISSUE TITLE
[BUG] Crash after completed the dialogue to get the quest (Landowner Needs Manual Laborers)

### ISSUE THREAD

**Issue by AJIexander** [TheOldRealms/TOW_Core#258]
**Describe the bug**

**To Reproduce**
1. Went to the village Zherden
2. Clicked to "visit" NPC 
3. Completed the dialogue to get the quest (Landowner Needs Manual Laborers)
4. Immediately after the dialogue, pressed "Tab"
5. Crash

**Times Reproduced**
The problem could not be reproduced.

**Expected behavior**

**Screenshots**

**Additional context**
[rgl_log_6264.txt](https://github.com/TheOldRealms/TOW_Core/files/8747287/rgl_log_6264.txt)
[rgl_log_errors_6264.txt](https://github.com/TheOldRealms/TOW_Core/files/8747288/rgl_log_errors_6264.txt)

**Save**
[Vampire_III.zip](https://github.com/TheOldRealms/TOW_Core/files/8747286/Vampire_III.zip)

**Comment by Jasonleh99** [comment]
Not reproducible on our end, closing now

Reach out to us on discord and we can help you personally
