### ISSUE TITLE
[BUG] Crash after clicked to "visit" NPC (Nanker of Gerhof) to get the quest

### ISSUE THREAD

**Issue by AJIexander** [TheOldRealms/TOW_Core#259]
**Describe the bug**
Crash after clicked to "visit" NPC (Nanker of Gerhof) to get the quest

**To Reproduce**
1. Went to the village Gerholf
2. Clicked to "visit" NPC (Nanker of Gerhof) to get the quest
3. Crash

**Times Reproduced**
It is possible to reproduce, there were three attempts.

**Expected behavior**

**Screenshots**

**Additional context**
[rgl_log_errors_13160.txt](https://github.com/TheOldRealms/TOW_Core/files/8747429/rgl_log_errors_13160.txt)
[rgl_log_13160.txt](https://github.com/TheOldRealms/TOW_Core/files/8747430/rgl_log_13160.txt)

**Save**
[Vampire_IV.zip](https://github.com/TheOldRealms/TOW_Core/files/8747428/Vampire_IV.zip)

**Comment by Jasonleh99** [comment]
Not reproducible on our end, closing now

Reach out to us on discord and we can help you personally
