### ISSUE TITLE
[BUG] Secondary firing method for blunderbuss crashes

### ISSUE THREAD

**Issue by R4MPZY** [TheOldRealms/TOW_Core#273]
The moment you try to fire with the secondary firing method for a blunderbuss the game will crash

**To Reproduce**
1. Go to any battle with a blunderbuss
2. Click on X to switch to secondary firing method
3. See error

**Times Reproduced**
2 out of 2

**Expected behavior**
I was expecting to see the second firing method but instead i get a hard CTD

BEW [here](https://drive.google.com/file/d/1mE7UoNf3ZZhDSoBNbWSZNrVvDLIK2zi-/view?usp=sharing)

**Comment by R4MPZY** [comment]
There is an issue with the blunderbuss where the secondary fire is able to be reloaded with regular musketballs;
-To be able to use the secondary fire method you need grenades, when you use up all grenades only use primary fire, if you reload with musketballs, press X for secondary fire and try to fire, it will crash.

**Comment by Z3rca** [comment]
the blunderbuss is not able to use both firemodes anymore. Several other problems arised, like ammunition was wrongly used or too many ammo was used. Therefore the whole behavior got changed on the 180 TOR version. closed
