### ISSUE TITLE
Vampires exist in all kingdoms/locations

### ISSUE THREAD

**Issue by Kysaro** [TheOldRealms/TOW_Core#40]
Vampires are to be found in any random location including stirland, averland etc.

Needs to be bound to Sylvania somehow.

**Comment by hunharibo** [comment]
This is a sideeffect of the vampire skin implementation. Anyone under age 22 (teenager maturity group) has a vampire skin. In order to "fix", we would have to patch the settlement notables spawning/implementation TW code. Most likely in UrbanCharactersCampaignBehavior

**Comment by Badulundabad** [comment]
Fixed by #81
