### ISSUE TITLE
Wind of magic increases when casting spells

### ISSUE THREAD

**Issue by atstrategist-droid** [TheOldRealms/TOW_Core#51]
When casting a spell, the winds of magic will increase instead of going down, and is also reset to 0 after a couple seconds

**Comment by helgibrandt** [comment]
Would look at this, but got no idea how exactly WoM supposed to work, is there any kind of GDD for this mechanic to read?

**Comment by hunharibo** [comment]
Solved with https://github.com/WarhammerTheOldWorld/TOW_CoreAssets/commit/2ee4d7bfe60082326e02550db62a3607a7757015
