### ISSUE TITLE
Ability crosshair implementation

### ISSUE THREAD

**Issue by Z3rca** [TheOldRealms/TOW_Core#52]
allow a special crosshair for each ability

**Comment by Badulundabad** [comment]
- Added a basic abstract crosshair class and its implementations for Projectile, Targeted, TargetedAOE, CenteredAOE, Summoning and MovingAOE abilities.
- Now AbilityTemplate has MinDistance and MaxDistance fields to limit the distance of the ability application, as well as CrosshairType field to indicate the type of crosshair used, also created CrosshairType enumeration.
- AbilityFactory initializes a crosshair and passes its link to ability.
- Now AbilityComponent has bool field IsAbilityModeOn.
- Modified AbilityManagerMissionLogic. If agent has abilities the player should press Q to enable/disable AbilityMode (AbilityComponent.IsAbilityModeOn turns to true). While the mode is on a current ability crosshair works and comes visible. Player is able to cast ability by pressing LMB. Casted ability uses crosshair position and direction, if crosshair is targeted it transfers an array of targets. Scrolling of mouse wheel is changing current ability.
- Changed the CustomCrosshairMissionLogic. If the ability mode is enabled, the weapon crosshair is disabled and the ability crosshair is turned on as mentioned above.

**Comment by Badulundabad** [comment]
To Do:
- add decals to crosshairs
- minimal distance limitation of MovingAOE crosshair don't work properly
- adjust logic of targets tranfering
- make that mission logics of abilities will not be added to mission if main agent has not abilities
