### ISSUE TITLE
Text Change - Culture Selection

### ISSUE THREAD

**Issue by Jaxy470** [TheOldRealms/TOW_Core#53]
![image](https://user-images.githubusercontent.com/88905514/129686184-2c1c3cad-5c47-4fcd-8cf7-9ea709fbf5c8.png)

Remove vanilla racial bonus text from culture selection screen

**Comment by Z3rca** [comment]
could be potentially fixed by a harmony patch... this might be for now enough. I am open for more elegant solutions

**Comment by hunharibo** [comment]
Fixed with xml in https://github.com/WarhammerTheOldWorld/TOW_CoreAssets/commit/b4aeb14957edb660bc67c8c7965b6612b4555cfb
