### ISSUE TITLE
Patching to 1.6.1 (Postponed)

### ISSUE THREAD

**Issue by Z3rca** [TheOldRealms/TOW_Core#58]
The patch could be really important, since people cant potentially  turn back to a outdated patch. Which in turn means, we will struggle that the mod is played at all. Therefore a patch is required... with all cons and pros of it.

**Comment by Z3rca** [comment]
for now we pause on this, since the patching created some rather big problems on the spawing of parties inside the world map.

**Comment by Z3rca** [comment]
apparently, somebody found a fix for this. I don't know if we should jump on this

**Comment by hunharibo** [comment]
its done. You can play with the branch 1.6.1-rc3
