### ISSUE TITLE
Calderia intro movie plays when starting a new campaign

### ISSUE THREAD

**Issue by LucasVanWijk** [TheOldRealms/TOW_Core#62]
When starting a new campaign the Bannerlord/Calderia intro video plays which is ofcourse not relevant for us.

**Comment by ShaneBadenhorst** [comment]
There are various ways of doing this HM patch (I am not to good at this) / overriding SandBoxGameManager (I have built a completely separate game mode that has it built in, which i plan to integrate after the game has been released)

Feel free to reach out to me @Dutchie (new guy)
