### ISSUE TITLE
Melee mode for guns

### ISSUE THREAD

**Issue by LucasVanWijk** [TheOldRealms/TOW_Core#63]
In the base game trowing weapons have a alternative melee mode. A similar implemantion for guns would be cool

Edit: I changed a little bit the heading. In principle a very nice idea, for multitude of problems... e.g. we can have different weapon modes for guns and magic staffs. 
- Z

**Comment by Z3rca** [comment]
i would look or ask the Swords and musket team, apparently they managed to have a Musket with bayonet.
