### ISSUE TITLE
Move Empire start position closer to city to prevent getting mugged easily

### ISSUE THREAD

**Issue by Matthew-Ross-1** [TheOldRealms/TOW_Core#71]
When starting an empire campaign I find myself getting mugged at least 3 times before reaching a city. I would recommend moving the start position closer.

The Vampire Counts start is fine.

**Comment by ShaneBadenhorst** [comment]
@Matthew-Ross-1 would spawning at the selected cultures city resolve this?

**Comment by Z3rca** [comment]
just move the spawn position close to  Wurtbad or Averheim or any other village.

**Comment by Badulundabad** [comment]
Fixed with https://github.com/WarhammerTheOldWorld/TOW_Core/commit/673a17e15d987dd95fcaeb46e803f9fda78375b8
