### ISSUE TITLE
Ability script works even if the game "on pause" 

### ISSUE THREAD

**Issue by Badulundabad** [TheOldRealms/TOW_Core#76]
[

https://user-images.githubusercontent.com/62873054/131692613-ff7859c1-4596-4674-bf42-6f3070ad1bb9.mp4

](url)

**Comment by martkartasev** [comment]
https://github.com/WarhammerTheOldWorld/TOW_Core/commit/0e72500f4d0655854151ae5fff6ee7f7e7e57f28
