### ISSUE TITLE
Shields colored with code color? Player shield shouldn't change

### ISSUE THREAD

**Issue by Z3rca** [TheOldRealms/TOW_Core#8]
Just something I noticed, every shield is just red, and do not have the any signs to identify the faction wielding the shield. I don't know if this is intended. 

Another thing what I think we should consider later: The player might be unaffected by this script. the shield should be one certain shape and color with logo and this needs to be assigned everytime.

**Comment by hunharibo** [comment]
It is set up to be faction specific, but only averland has entries in the xml. For all the other factions it should fall back to the generic white-red empire ones that is culture specific. Vamps shouldnt even have that, for them, the normal kingdom colors should show. We will get some new ones soon.
