### ISSUE TITLE
Biberhof child icon 

### ISSUE THREAD

**Issue by Rob640** [TheOldRealms/TOW_Core#83]
Biberhow shows a npc icon under a child 
![unknown (2)](https://user-images.githubusercontent.com/54803908/132994380-dbbe2c47-935a-4cc3-bfbb-b3c729a583b4.png)

**Comment by Badulundabad** [comment]
![Biberhof](https://user-images.githubusercontent.com/62873054/133311565-2c978ab2-4290-45ec-920a-afca787ae9a0.png)

**Comment by Z3rca** [comment]
didn't find it might be now irrelevant
