### ISSUE TITLE
Leicheberg 

### ISSUE THREAD

**Issue by Rob640** [TheOldRealms/TOW_Core#84]
every time i try to play the Leicheberg siege my game crashs.

In custom battle: at the end of the loading screen I hear a crowd like if i'm loading in a city scene for walking through it (like in the campaign)

In campaign: when I besiege the town I can load on the siege scene but when I press the play button, my game crashs

**Comment by debarr1** [comment]
This has been confirmed by the user [CptCrimson](https://discord.com/channels/702088927380635678/886588234820374539/891678503429341205) who generated [this](https://drive.google.com/file/d/1D6Ysh4gRpZRYpsDoKjPehfKx8n5CAyJo/view?usp=sharing) crash file.

Loading this file in 1.6.2 - development I was able to reproduce the bug as seen [here](https://streamable.com/m92ptw) generating [these](https://drive.google.com/file/d/13sJVhOMjmyFP9HrqIHRnyCjeDNV3pJXL/view?usp=sharing) crash files.  Discarding all equipment prior to the stroll did not change the outcome.  [Video](https://streamable.com/0554vt) - [files](https://drive.google.com/file/d/1D5uzc5D9jm-MQryfkDeVtqCCdoM6dGA1/view?usp=sharing).
