### ISSUE TITLE
Random crashes

### ISSUE THREAD

**Issue by Badulundabad** [TheOldRealms/TOW_Core#87]
### Known cases:
- upgrading skeletons
- entering a village as the vampire
- walking around on the campaign map
- decapitating people
- entering eichestatten, and interacting with tavern menu, as well as trade and inventory.
- running down fleeing bandits, killing them after a battle's over
- opening inventory snd pressing cancel or done, entering towns, after battles, asking certain npcs certain questions
- entering the tavern at Averheim. Also if its relevent I had just won a tournament there and attached an imperial gauntlet that I won
- as Vampire Lord when I went to help a Caravan under attack
- using the Rusty Grave Guard Great-axe with the slow motion beheading feature, this is a weird one. so the screenshot below shows the game "crashing" while doing this but this is different, i can still use rts-camera mod and use the Esc key to leave the battle but everything in the battle's completely frozen, very strange and the first time its happened like this 
- standing around city, no battles
- using the Empire rapier and beheading someone, but vanilla ridged saber didn't crash
- doing all that forces the game to generate portraits

**Comment by Badulundabad** [comment]
[some_random_crash_reports.zip](https://github.com/WarhammerTheOldWorld/TOW_Core/files/7157146/some_random_crash_reports.zip)

**Comment by Badulundabad** [comment]
### Pretty rarely you can see this
![d3d_createTexture](https://user-images.githubusercontent.com/62873054/133239578-69b53bb2-5b2c-444b-b1a0-74b5a5df144b.png)

**Comment by martkartasev** [comment]
https://github.com/WarhammerTheOldWorld/TOW_CoreAssets/commit/915793761c8cf083900475baaddd3475ec5107c4
https://github.com/WarhammerTheOldWorld/TOW_CoreAssets/commit/b61d1dc45f7959ded4239d3a844ca5cde0ea09e4

Fixes many of the crashes. Will have to see if any of the others still exist.
