### ISSUE TITLE
Rebalance of bandits weapon

### ISSUE THREAD

**Issue by Badulundabad** [TheOldRealms/TOW_Core#93]
### There are some messages from fans below:
- And it should be so, simple robbers kill me with one blow, I am in vampire armor) and level 29.
- Hmm does anyone else have face secessionist spearman ? They seam to deal a hack of a lot of damage. 116 on one hit ?
- The starting outlaws feel REALLY overtuned. An Outlaw Captain just hits you with a clean 151, OHKed my horse and then me

**Comment by Z3rca** [comment]
Spears are recently scaled down
