### ISSUE TITLE
Change vampire roster

### ISSUE THREAD

**Issue by Badulundabad** [TheOldRealms/TOW_Core#94]
How can be skeleton upgraded to vampire? I know that we haven't so much troops for Vampire counts, but we can change the roster, so it look more logically.

**Comment by Badulundabad** [comment]
![weird_vampiric_roster](https://user-images.githubusercontent.com/62873054/133321578-e74943a3-4b84-40f1-b27d-12a9d2bae395.png)

**Comment by Z3rca** [comment]
fixed with new troop tree
