### ISSUE TITLE
Replace expensive equipment of companios to cheap one

### ISSUE THREAD

**Issue by Badulundabad** [TheOldRealms/TOW_Core#96]
### There are some fan notices:
- you can hire Witch hunter for 2000 and gain 25000 for his pistol
- starting as a vampire gives you a pureblood horse and marius leitdorfs gloves which are worth 60k gold alone not sure if thats intentional
- bretonnain knight called fredrick i think i recruited him as a member of my party then i noticed he had better gear then me so i took his gear then i noted he had a second pair on his "walk though town" set and i sold his second set for 60k gold keep in mind recruiting him only cost me 2k. the last part is not a bug but something i found to be slightly odd

**Comment by Z3rca** [comment]
No relevance now, that is a mayor balance problem that needs to be faced later
