### ISSUE TITLE
Remove native troops

### ISSUE THREAD

**Issue by Badulundabad** [TheOldRealms/TOW_Core#98]
![raiders_from_escort_caravan_quests_are_vanilla](https://user-images.githubusercontent.com/62873054/133323857-99e32443-e293-485a-af63-579f3a3231ba.jpg)
![mountain_bandit_boss](https://user-images.githubusercontent.com/62873054/133324065-79651923-3b46-4a68-bbb3-8970e623e53a.jpg)
![forest_bandit_boss](https://user-images.githubusercontent.com/62873054/133324068-3a1e45e6-63c7-46fc-9a3b-0a4b37534ef4.jpg)

**Comment by Badulundabad** [comment]
Also it needs to remove mounted ransaker on Caravan Ambush mission

**Comment by Z3rca** [comment]
fixed
