### ISSUE TITLE
Replace dialogues for chaos warriors

### ISSUE THREAD

**Issue by Badulundabad** [TheOldRealms/TOW_Core#99]
![good_day_by_berserk](https://user-images.githubusercontent.com/62873054/133325499-174a8bf4-4e69-4846-9805-430e0917c952.png)

**Comment by Z3rca** [comment]
![grafik](https://user-images.githubusercontent.com/43908801/164537639-c9689b37-b24b-4089-ac0e-15c955e3f58d.png)
was recently done
